### ISSUE TITLE
Git SSH support

### ISSUE THREAD

**Issue by hugomd** [henrikdahl/hyper-statusline#31] opened 2017-02-01 06:16 UTC
It would be nice if clicking the branch name took you to the branch if the remote is git via SSH rather than HTTPS.

**Comment by henrikdahl** [comment] 2017-02-04 23:00
@hugomd could you elaborate?

**Comment by hugomd** [comment] 2017-02-04 23:23
@henrikdahl If I `cd` into a git repository, the bottom right hand corner gives a link to the branch I'm on: ![](http://hu.md/9mj1.png)

This works fine if I've cloned using HTTPS, and opens my browser and takes me to the repository. If I've cloned using SSH then it opens a new terminal window rather than opening the browser.

**Comment by henrikdahl** [comment] 2017-02-04 23:28
@hugomd are you saying it currently opens a new terminal window when you've cloned with SSH or that it's the expected behavior you'd like to see?

**Comment by hugomd** [comment] 2017-02-05 10:37
@henrikdahl It opens a new terminal window when I've cloned with SSH and click on `master`, but it would be great if it could open the repository in the default browser — not sure if that's feasible or not though.

**Comment by henrikdahl** [comment] 2017-02-05 11:17
@hugomd mind sharing how your remote url looks?

**Comment by henrikdahl** [comment] 2017-02-14 13:21
It should already do what you're suggesting, which is why it would be useful to see what your remote url looks like. I'm closing this for now ✌️

**Closed by henrikdahl** 2017-02-14 13:21 UTC

**Comment by hugomd** [comment] 2017-02-14 22:38
@henrikdahl Totally missed this, sorry! It seems to work for GitHub, but not GitLab — I'll look into it myself and see if I can work it out myself and maybe make a PR.

**Comment by hugomd** [comment] 2017-02-14 22:45
@henrikdahl Found it. Issue is caused by [L167](https://github.com/henrikdahl/hyper-statusline/blob/master/index.js#L167). 

If the git remote uses any port other than 22 it won't work. E.g. 

```JavaScript
> remote = "ssh://git@git.hu.md:1022/hugo/dotfiles.git";
'ssh://git@my.hosted.git:1022/hugo/myrepo.git'
> curRemote = remote.trim().replace(/^git@(.*?):/, 'https://$1/').replace(/[A-z0-9\-]+@/, '').replace(/\.git$/, '');
'ssh://my.hosted.git:1022/hugo/myrepo'
```

Expected output should be:
`https://my.hosted.git/hugo/myrepo`
Output causing issue is currently:
`ssh://my.hosted.git:1022/hugo/myrepo`

**Comment by henrikdahl** [comment] 2017-02-15 01:54
How come your remote includes `ssh://`? It should work without it and GitLab doesn't add it by default.

Input
<img width="568" alt="skarmavbild 2017-02-15 kl 02 54 11" src="https://cloud.githubusercontent.com/assets/1430576/22957656/0fe56252-f32a-11e6-9d1e-aed0242d2b44.png">

Output
<img width="308" alt="skarmavbild 2017-02-15 kl 02 54 30" src="https://cloud.githubusercontent.com/assets/1430576/22957663/192ed7ee-f32a-11e6-894f-843695f02fec.png">

**Comment by hugomd** [comment] 2017-02-15 02:45
I'm running a self-hosted instance of GitLab, which uses a different port. When you do that, GitLab pops ssh:// in front of it.

**Comment by henrikdahl** [comment] 2017-02-15 03:14
So I'm not sure how to solve this. `ssh://` part is easy since the regex can simply check for any character before the `@` symbol instead of specifically `git`.

However the port part is identical to the username part.

`ssh://git@my.hosted.git:1022/hugo/myrepo.git`
`git@github.com:henrikdahl/hyper-statusline.git`

Since a username can be numbers as well, there's really no way to identify which it is. Any suggestion for a pattern thats consistent? ✌️

**Comment by hugomd** [comment] 2017-02-15 03:18
You could check to see if it starts with `ssh://`, and if it does then remove what's immediately after the `ssh://git@my.hosted.git:` 

There might be a simpler way though

**Comment by henrikdahl** [comment] 2017-02-15 03:19
Someone could have `ssh://` even though they don't have a port, it would mess up their URLs so it's not fully reliable.

**Comment by hugomd** [comment] 2017-02-15 03:28
@henrikdahl That's true — I'm not sure how I'd recommend fixing it then. I'll try changing my GitLab port to 22 for now! 👍 

Thanks for dealing with the issue!

**Comment by hugomd** [comment] 2017-02-15 22:40
@henrikdahl Is the port always followed by a `/`? If so you could regex select a number followed by a `/`, while still allowing the previous usage.

**Comment by henrikdahl** [comment] 2017-02-15 22:42
@hugomd Problem is that a username could be numbers and follow the exact same pattern.

**Comment by hugomd** [comment] 2017-02-15 22:43
@henrikdahl I understand that but `/` isn't allowed in usernames, and separates the two.
